[build]
  command   = "npm run build"
  publish   = "dist"
  environment = { VITE_API_URL = "https://your-backend-api-domain/api" }

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-api-domain/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
